### ISSUE TITLE
requires browser history?

### ISSUE THREAD

**Issue by Evanion** [beerpay/beerpay-browser-extension#1]
Why have the extension suddenly started to require access to browser history?
What function requires this type of access?

**Comment by colkito** [comment]
Oh! a little cleanup was missing after tests.
Fixed on this commit https://github.com/beerpay/beerpay-browser-extension/commit/19d1191362e5cc12e2ebc49c590619a31424952d (V2.1.1)
Current published version: `v2.1.3`

Thanks for notice @Evanion!🙌

I'll close this issue. Feel free to reopen or comment.
